#!/bin/bash

SRC=$(pwd)
DEST=$HOME

function die {
	echo $1 >&2
	exit 1
}

if [ ! -f $SRC/setup ]; then
	die "Script must be run inside the dotfiles repository."
fi

# Git
install -m 400 $SRC/git/gitconfig $DEST/.gitconfig

# GnuPG
install -D -m 400 $SRC/gnupg/gpg.conf $DEST/.gnupg/gpg.conf
#install -m 400 $SRC/gnupg/gpg-agent.conf $DEST/.gnupg/gpg-agent.confa

# i3
install -D -m 400 $SRC/i3/config $DEST/.config/i3/config

# i3status
install -D -m 400 $SRC/i3/status/config $DEST/.config/i3status/config

# Sakura
install -D -m 400 $SRC/sakura/sakura.conf $DEST/.config/sakura/sakura.conf

# SSH
install -D -m 400 $SRC/ssh/config $DEST/.ssh/config
install -D -m 400 $SRC/ssh/authorized_keys $DEST/.ssh/authorized_keys

# TMUX
install -m 400 $SRC/tmux/tmux.conf $DEST/.tmux.conf

# VIM
install -m 400 $SRC/vim/vimrc $DEST/.vimrc
