#!/bin/bash

SRC=$(pwd)
DEST=$HOME

function die {
	echo $1 >&2
	exit 1
}

if [ ! -f $SRC/setup ]; then
	die "Script must be run inside the dotfiles repository."
fi

# Curl
install -m 400 $SRC/curl/curlrc $DEST/.curlrc

# Environment
install -m 500 $SRC/profile $DEST/.profile

# Git
install -m 400 $SRC/git/gitconfig $DEST/.gitconfig

# GnuPG
mkdir -p $DEST/.gnupg
install -m 400 $SRC/gnupg/gpg.conf $DEST/.gnupg/gpg.conf

# SSH
mkdir -p $DEST/.ssh
chmod 700 $DEST/.ssh
touch $DEST/.ssh/known_hosts
install -m 400 $SRC/ssh/config $DEST/.ssh/config
install -m 400 $SRC/ssh/authorized_keys $DEST/.ssh/authorized_keys
mkdir -p $DEST/.ssh/controlmasters
chmod 700 $DEST/.ssh/controlmasters
chmod 500 $DEST/.ssh

# TMUX
install -m 400 $SRC/tmux/tmux.conf $DEST/.tmux.conf

# VIM
install -m 400 $SRC/vim/vimrc $DEST/.vimrc

# zsh
install -m 400 $SRC/zsh/zshrc $DEST/.zshrc
install -m 400 $SRC/zsh/zprofile $DEST/.zprofile

if [ "$(uname -s)" == "Darwin" ]; then
	exit
fi

# i3
#install -D -m 400 $SRC/i3/config $DEST/.config/i3/config

# i3status
#install -D -m 400 $SRC/i3/status/config $DEST/.config/i3status/config

# Sakura
#install -D -m 400 $SRC/sakura/sakura.conf $DEST/.config/sakura/sakura.conf

# Feh
#install -m 500 $SRC/feh/fehbg $DEST/.fehbg
#install -m 400 $SRC/feh/fehbg.jpg $DEST/.fehbg.jpg

# X11
#install -m 500 $SRC/xinitrc $DEST/.xinitrc
