autocmd!

set nocompatible
set viminfo=

" Move vertically in wrapped lines
nnoremap j gj
nnoremap k gk

" Pretty UI
set cursorline
set wildmenu

" Search
set incsearch
set hlsearch

" Fold
set foldenable

" Sane backspace
set backspace=indent,eol,start

" Share system clipboard
set clipboard=unnamed

" Enable filetype-specific settings
filetype on
filetype plugin on
filetype indent on

" Disable line wrapping by default
set linebreak
set nowrap

" Syntax hilighting, yes please!
syntax on
set showmatch

" Enable mouse support
set mouse=a

" Make sure there are 5 lines visible around the cursor
set scrolloff=5

" Indenting with tabs
set smartindent
set shiftwidth=3
set tabstop=3
set softtabstop=3

" Line numbers
set number

" Status line
set laststatus=2

" Working in a terminal with dark backgrounds.
set background=dark

" Always use unix-style line endings
set fileformats=unix
set ff=unix

set lazyredraw

" Language specific settings
autocmd FileType tex setlocal wrap
autocmd FileType md setlocal wrap
autocmd Filetype ruby setlocal ts=2 sts=2 sw=2 expandtab
